# 服务器配置
server:
  port: 8080
  tomcat:
    threads:
      max: 1500
      min-spare: 50
    uri-encoding: UTF-8
    accept-count: 750
    max-connections: 10000
    connection-timeout: 30000ms

# 数据源配置
spring:
  datasource:
    # 主数据源
    master:
      name: cmall-datasource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/CMall?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useAffectedRows=true
      username: root
      password: AaZz112211
      #    连接池
      hikari:
        pool-name: hikariCP-master
        auto-commit: true
        #      minimum-idle: 20
        maximum-pool-size: 1500
        idle-timeout: 600000
        max-lifetime: 30000
        connection-timeout: 30000
    # 从数据源
    slave:
      name: cmall-datasource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3307/CMall?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useAffectedRows=true
      username: root
      password: AaZz112211
      #    连接池
      hikari:
        pool-name: hikariCP-slave
        auto-commit: true
        #      minimum-idle: 20
        maximum-pool-size: 1500
        idle-timeout: 600000
        max-lifetime: 30000
        connection-timeout: 30000
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 123456
      connect-timeout: 5000ms
      timeout: 5000ms
      client-type: lettuce
  servlet:
    multipart:
      max-file-size: 2MB

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    disable-swagger-default-url: true