# 数据源配置
spring:
  datasource:
    name: cmall-datasource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CMall?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 12123312
    #    连接池
    hikari:
      pool-name: hikariCP
      minimum-idle: 20
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 123456
      connect-timeout: 5000ms
      timeout: 5000ms
      client-type: lettuce