package com.tsong.cmall.dao;

import com.tsong.cmall.entity.AdminUser;
import java.util.List;

/**
 * @Author: Tsong
 * @date: 2023/03/20/02:39
 */
public interface AdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_user
     *
     * @mbg.generated Mon Mar 20 02:39:50 CST 2023
     */
    int deleteByPrimaryKey(Integer adminUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_user
     *
     * @mbg.generated Mon Mar 20 02:39:50 CST 2023
     */
    int insert(AdminUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_user
     *
     * @mbg.generated Mon Mar 20 02:39:50 CST 2023
     */
    AdminUser selectByPrimaryKey(Integer adminUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_user
     *
     * @mbg.generated Mon Mar 20 02:39:50 CST 2023
     */
    List<AdminUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_user
     *
     * @mbg.generated Mon Mar 20 02:39:50 CST 2023
     */
    int updateByPrimaryKey(AdminUser row);
}