package com.tsong.cmall.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_admin_user
 */
/**
 * @Author: Tsong
 * @date: 2023/03/20/02:39
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AdminUser {
    /**
     * Database Column Remarks:
     *   管理员id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.admin_user_id
     *
     * @mbg.generated Mon Mar 20 02:39:50 CST 2023
     */
    private Integer adminUserId;

    /**
     * Database Column Remarks:
     *   管理员登陆名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.login_user_name
     *
     * @mbg.generated Mon Mar 20 02:39:50 CST 2023
     */
    private String loginUserName;

    /**
     * Database Column Remarks:
     *   管理员登陆密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.login_password
     *
     * @mbg.generated Mon Mar 20 02:39:50 CST 2023
     */
    private String loginPassword;

    /**
     * Database Column Remarks:
     *   管理员显示昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.nick_name
     *
     * @mbg.generated Mon Mar 20 02:39:50 CST 2023
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   是否锁定 0未锁定 1已锁定无法登陆
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.locked
     *
     * @mbg.generated Mon Mar 20 02:39:50 CST 2023
     */
    private Byte locked;
}